name: BiomeChatRelay
version: ${project.version}
author: husK
main: pw.biome.biomechatrelay.BiomeChatRelay
api-version: 1.16
depend: [ BiomeChat ]
commands:
  biomechatrelay:
    description: commands
    usage: /biomechatrelay
    aliases: [ bcr ]